### ISSUE TITLE
[universal-redux] How to apply global styles?

### ISSUE THREAD

**Issue by 0xsven** [diegohaz/arc#10]
Awesome boilerplate!

Until today I was using the master branch to work on components. Like in your examples I was using `injectGlobal` from styled-components to add webfonts, root font size and some base styles for html and body elements. 

Today I decided to try the server side rendering branch. I realised that `injectGlobal` runs on page load. That causes a small glitch in the UI because the browser first displays the page without said styles and then injects them only after first render.

Using a styles.css solves that issue. I was wondering if you have a better solution to that?

**Comment by diegohaz** [comment]
Thank you for the feedback, @0xsven.

There's an open issue (https://github.com/styled-components/styled-components/issues/124#issuecomment-255678841) on styled-components repo for that. While this isn't solved, the `styles.css` is the way to go.

**Comment by diegohaz** [comment]
@0xsven It was my fault. I put it inside `componentDidMount`, which doesn't run on server. If you put `injectGlobal` on `componentWillMount` it works.
