### ISSUE TITLE
Move docs to GitHub Wiki

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/arc#100]
Docs size will increase and we would need to whether add a `docs` folder or move them to the repository Wiki.

Although keeping a `docs` folder could be useful for projects based on ARc, this isn't the case of most projects. Most of people (I'm assuming) will want to remove that folder.

Let's use Wiki so we don't add one more setup step.

**Comment by kybarg** [comment]
@diegohaz That would be nice. I think that's better not to overload project with docs and keep them at Wiki.

**Comment by protoEvangelion** [comment]
@diegohaz @kybarg Not to diminish kybar's work at all, but what do you all think of using a structure similar to what Facebook/React does.  That is:

1.  Have very minimal docs on **main github** page
2.  List updates, resources, and other minutia on the **wiki page**
3.  List the full docs in all their glory on the **username.github.io** site

I would be happy to help implement this if you are game!

**Comment by diegohaz** [comment]
https://github.com/diegohaz/arc/wiki
