### ISSUE TITLE
[redux] Reusable form

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#104]
Hello! I'm quite new to redux, moreover redux-saga. And after days of digging haven't found any simple example of "reusable" form. I want the same form to be used to create/update some entity. Also please make more detailed example for common CRUD actions. Thanks

**Comment by diegohaz** [comment]
You can use the same form component, but with different containers, one for creation and another for update (take the `PostForm` as example).

Which kind of CRUD action is missing from the generic/post example actions?

**Comment by kybarg** [comment]
@diegohaz Yes i did separate containers. But now when I want to create new post there is still data of previous category... I think I don't even need to put post I want to edit into store. Or how to clear state when ID pram is missing?
As for the CRUD example I would like to have to see:
1. Page with list of items (already there))
2. Page displaying single item - view action
3. Page for editing existing item
4. Page for creating new item (already there)
5. Delete action (already there but doesn't have real example)

I did that everything, but it look as "frankenstein" to me) I would be glad to see proper example, extended version of posts component. Thank you.

**Comment by diegohaz** [comment]
You can find answers in redux/redux-saga related channels (StackOverflow, Slack, Discord, GitHub etc.).

And take a look at this project: https://github.com/tramaLabs/web (it has the single item action).

Please, post here when you figure out those things (can help others). :)

**Comment by kybarg** [comment]
@diegohaz I will make PR so you could review it. Ok?

**Comment by diegohaz** [comment]
@kybarg Sure 👍

**Comment by kybarg** [comment]
Closing due #108
