### ISSUE TITLE
HMR doens't work

### ISSUE THREAD

**Issue by zj5121** [diegohaz/arc#107]
simply cloned the universal-redux branch, but HMR doesn't work, the browser doesn't update due to any change. In the browser, there is an error:

GET http://0.0.0.0:3001/app.faa40ac9d7e2f9de2fc7.js net::ERR_CONNECTION_REFUSED

node --version
v6.9.5

**Comment by zj5121** [comment]
looks it's because publicPath in webpack.config.js is not correct:

output: {
  publicPath: DEBUG ? `http://${ip}:${port}/` : PUBLIC_PATH
}

since ip == '0.0.0.0', it will use the 0.0.0.0 in real request, that's wrong definitely.
It should be the server IP determined in client browser instead of '0.0.0.0'.

Anyway to implement that?

Thanks

**Comment by diegohaz** [comment]
Hi, @zj5121. It works for `0.0.0.0`, `localhost`, `127.0.0.1` etc. What's the IP you are running?

You can always `IP=192.168.25.2 npm run dev`.

**Comment by zj5121** [comment]
Thanks, it works now.
