### ISSUE TITLE
[universal-redux] Global styles applied several times now

### ISSUE THREAD

**Issue by 0xsven** [diegohaz/arc#11]
After your latest bug fix (moving globalInjects to componentWillMount) global styles are applied several times on the server. 

On your demo page (https://arc.diegohaz.com/) the global styles are applied 3 times. In my app which has a little more global styles, they are applied up to 12 times. It seems like this grows over time.

I will investigate a little and post my findings.

**Comment by diegohaz** [comment]
Maybe we need to move `injectGlobal` to outside the component. I'm not able to test this right now. Can you see if this works?

**Comment by 0xsven** [comment]
I just realised that it adds up with every page refresh

**Comment by diegohaz** [comment]
It makes sense. `App` is mounted on every page refresh. the `*Mount` methods aren't the right place for`injectGlobal` indeed.

**Comment by diegohaz** [comment]
I mean something like this:
```js
injectGlobal`
body {
margin: 0;
}
`

class App extends Component {
...
```

**Comment by 0xsven** [comment]
That works!

**Comment by diegohaz** [comment]
Nice! Would you mind to send a PR with this on master (I merge with other branches later)?

The files are `src/components/App.js` and `src-clean/components/App.js`
