### ISSUE TITLE
[proposal] JSS integration example

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#111]
Recently have switched my ARC based project to [jss](https://github.com/cssinjs/jss), because want full integration with [material-ui@next](https://github.com/callemall/material-ui/tree/next) and this is too expensive to have two CSS engines with mostly the same functionality in one project.
Do we need another branch with **Material UI** and **JSS**  integration? Or it will be hard to maintain so many branches?

**Comment by diegohaz** [comment]
I don't know how hard it'll be. Maybe this is the case for a `arc-jss` fork? Do you want to work on that?

**Comment by diegohaz** [comment]
Closing this for now. I'll reopen it if someone wants to work on that. 👍
