### ISSUE TITLE
Generate static imports for correct indexing

### ISSUE THREAD

**Issue by advance512** [diegohaz/arc#113]
An issue I have encountered is that because of arc's dynamic style of importing:

```
const req = require.context('.', true, /\.\/[^/]+\/[^/]+\/index\.js$/)

req.keys().forEach((key) => {
  const componentName = key.replace(/^.+\/([^/]+)\/index\.js/, '$1')
  module.exports[componentName] = req(key).default
})
```

WebStorm (and I am sure other IDEs) completely loses its ability index the source, hence to "Go To Definition", "Auto Import" etc - which is highly annoying and costs productivity.

A simple way to fix it would be to add a:

```
export * from './index.optimized'
```

This index.optimized.js will basically be a "dump" of the output of the module dynamically generated:

```
export Header from './organisms/Header'
export Footer from './organisms/Footer'
..
..
```

So importing it will change nothing. This file can quite easily be generated, and should be generated on instantiation of the arc-generator when working in dev mode.

What do you think?

**Comment by diegohaz** [comment]
Please, take a look at the project on this commit: https://github.com/diegohaz/arc/tree/0b9cacb2767a77ac4ea55f0a8c8c5b6c757ebac0/src/components

It had had an `index.js` file on each component type folder exporting all components inside that folder (at that time we still didn't have `generator-arc` so adding components was a pain in the ass).

I'm aware of this problem with tooling and I find your solution very elegant. We just need to improve `generator-arc` to handle this.

**Comment by diegohaz** [comment]
Closing this in favor to #131
