### ISSUE TITLE
Example in 'fullstack' branch has components that import containers

### ISSUE THREAD

**Issue by advance512** [diegohaz/arc#114]
...is this not an anti-pattern?

**Comment by diegohaz** [comment]
It's ok. 

Here you can see the reasons and benefits: http://redux.js.org/docs/faq/ReactRedux.html#should-i-only-connect-my-top-component-or-can-i-connect-multiple-components-in-my-tree

There're two downsides:
- It can be harder to test. But we do mock all components/containers on testing ([here](https://github.com/diegohaz/arc/blob/0e7b8e93cdf043d61b3d790cd5c14d718b531d95/test/componentsMock.js))
- It can be harder to see how data flows. But once you have all your containers in one place and don't add any presentational logic to them it becomes really easy (from my experience on a project with ~100 components and ~15 containers).

**Comment by advance512** [comment]
Thanks for your input.
I tend to think that Pages should be a 3rd category, next to Containers and Components. Not sure though.
