### ISSUE TITLE
[universal-redux] componentDidMount in client.js

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#119]
How can I define **componentDidMount** in **client.js**?

**Comment by diegohaz** [comment]
Why do you want to do that? I would do that on the `App` component.

**Comment by kybarg** [comment]
@diegohaz want to clear SSR styles

**Comment by diegohaz** [comment]
@kybarg Let's use the chat for things like this
https://gitter.im/atomic-react/Lobby
