### ISSUE TITLE
Upcoming changes on branch structure

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/arc#120]
Hey, guys, I want to share with you what I'm planning to do with branch structure.

Actually, they are small changes:

1. As I explained in https://github.com/diegohaz/arc/issues/112#issuecomment-280871584 and https://github.com/diegohaz/arc/issues/106#issuecomment-280900093, I'll stop to maintain the `fullstack` branch. I'm open for anyone who wants to take this (whether with the branch here as a collaborator or with a fork);

2. Branch name should reflect better from which other branch it comes from. For example:
    ```
    master
    |_ redux
        |_ redux-graphql
        |_ redux-ssr
            |_ redux-ssr-graphql
    ```

    That said, I plan to rename `universal-redux` to `redux-ssr`, which better reflects what it is. I'm not sure how this could impact the current references to `universal-redux` though.

    The `-graphql` ones are just examples of what we could do with further features like #106.

It's open for discussion, but I plan to have this on `v0.8`, which will be there in about a month.

**Comment by protoEvangelion** [comment]
@diegohaz Any updates on maintaining the `fullstack` branch or changing the branch structure?

**Comment by diegohaz** [comment]
@protoEvangelion I'm still maintaining the fullstack branch, and I started a `redux-ssr` branch, but not ready yet.

**Comment by ajhool** [comment]
Need any specific help on fullstack? I thought you had dropped fullstack
support, but I think it's really valuable

**Comment by protoEvangelion** [comment]
@diegohaz Thanks!  @ajhool Nothing specific...just curious where things are headed :)

**Comment by diegohaz** [comment]
One of the reasons that made me consider dropping support on `fullstack` was that I'm not using it on any project of mine. So it would be better to "give" it for another maintainer who is actually using it.

But I'll keep accepting/reviewing PRs.

**Comment by protoEvangelion** [comment]
@diegohaz This repo feels a bit bloated with the **redux** and **universal-redux** branches because we already have the **redux-ssr** branch.

For the sake of simplifying contributions and on boarding for new comers, it may be beneficial to drop the **redux** and **universal-redux** branches.

**_Do the pros outweigh the cons for keeping these two branches around?_**

**Comment by diegohaz** [comment]
@protoEvangelion `redux-ssr` isn't ready yet. I've just played with it. The official branches are still those listed on README.md. 

`redux-ssr` will replace `universal-redux`. But we still need a `redux` branch without SSR (actually, most of my React projects are based on the redux branch).

**Comment by protoEvangelion** [comment]
@diegohaz  Got it.  I just assumed everyone would prefer SSR because of all of the benefits it brings

**Comment by diegohaz** [comment]
The downside of SSR is that you can't host it on GitHub Pages. 😕
