### ISSUE TITLE
Replace axios by isomorphic-fetch

### ISSUE THREAD

**Issue by 7s4r** [diegohaz/arc#121]
Hi Diego,

It will be nice if we can replace axios by [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) as fetch API will become a standard.

I've already done this job in one of my project based on arc.

What do you think?

**Comment by diegohaz** [comment]
Yeah, I do agree with that. 👍

**Comment by 7s4r** [comment]
Ok, I will create a PR asap.

**Comment by 7s4r** [comment]
Done: https://github.com/diegohaz/arc/pull/125

**Comment by diegohaz** [comment]
Fixed in #125
