### ISSUE TITLE
Update docs for how to deploy to a non Heroku server

### ISSUE THREAD

**Issue by rtirserio** [diegohaz/arc#145]
The docs say how to deploy to Heroku but not everyone uses Heroku. It would be helpful to have instructions showing how to build and then run using a more general node setup (forever for example).

I'm happy to PR this change if I can figure out how to do it

**Comment by diegohaz** [comment]
It would be nice to have docs for other services. 👍

**Comment by zj5121** [comment]
This is also what I'm looking for.
Actually, I don't know how to deploy this after the 'npm run build', there is only a 'app.xxx.js' there, no html file shown, how could I run this code?
Thanks!

**Comment by diegohaz** [comment]
@zj5121 If you are using `universal-redux` or `fullstack`, you need to deploy everything on a NodeJS (> 6) environment and use `npm start`.

**Comment by zj5121** [comment]
good to know that :)
I'm using fullstack, so that means I have to copy all my source code except for node_modules to the vps, right?
Thanks!

**Comment by diegohaz** [comment]
Yeah, usually everything that isn't in .gitignore

**Comment by zj5121** [comment]
got it, thanks!

**Comment by diegohaz** [comment]
I'll close this for now.

Any other examples are welcome here: https://github.com/diegohaz/arc/wiki/Deploy
