### ISSUE TITLE
Containers modules exported twice

### ISSUE THREAD

**Issue by santino** [diegohaz/arc#149]
The containers index is grabbing all containers using the following code
`const req = require.context('.', false, /^((?!index).)*$/)`

This causes each file to be processed 2 times, taking the example of the `Generic.js` file this is first processed as `./Generic` and then again as `./Generic.js` which causes the module to be exported 2 times the first with name `./Generic` and the second with name `Generic`.
This can be verified by logging `key` and `containerName` in `/containers/index.js` after line 4.

We want only the second process/export to happen.

**Comment by diegohaz** [comment]
Fixed in #150
