### ISSUE TITLE
How to scale multiple forms?

### ISSUE THREAD

**Issue by steven-haddix** [diegohaz/arc#16]
I'm playing through the universal redux example and I'm curious what the proper way to scale the application to have potentially dozens of forms? 

Would you reuse the forms actions but have a different container for each form?

**Comment by diegohaz** [comment]
Hi, @steven-haddix 

I create a container and an organism component for each form, reusing the `Field` component.

I can give you a better answer if you share the snippet of code you are doing.

**Comment by steven-haddix** [comment]
I don't have anything in a repo just yet. Mostly exploring the architecture and seeing how things work.

Do the forms all share the same store/form functions?

**Comment by diegohaz** [comment]
> Do the forms all share the same store/form functions?

They share some, but not all. A `PostCreationForm`, for example, calls `postCreate` from store; a `LoginForm` would call something from an `auth` store; and so on.
