### ISSUE TITLE
Applying the social login to other applications

### ISSUE THREAD

**Issue by declanelcocks** [diegohaz/arc#164]
I'm using your social login sagas from this project, and wondered if you'd implemented something similar with an OAuth application such as GitHub? For Facebook and Google I see you're injecting the official script and executing it in order to authorize with that service, but how about something like GitHub where a script might not be available?

I'm asking because in another project I tried to use `passport-github` but the whole callback URL logic got me into a mess, and your FB/Google saga logic is pretty awesome.

**Comment by diegohaz** [comment]
GitHub login is quite different than Google/Facebook. There's also an open issue on another project I maintain (https://github.com/diegohaz/rest/issues/8).

I'll not be able to implement that so soon, but it would be a great enhancement if someone wants to help. :)

**Comment by declanelcocks** [comment]
Will give it a try with GitHub and report back 👍

**Comment by declanelcocks** [comment]
Hey @diegohaz just had a couple of hours to play with this idea and wanted your thoughts. I figured if I wanted to implement several social logins then I would need something a bit more reusable and maintainable for each login.

Anyway, I've implemented a set of sagas which does the following:
- launches a popup to obtain a token from GitHub
- Call the Arc API to verify the token with GitHub
- Save or update a User in the DB and generate a token
- Send { token, user } to the client
- Close the popup and place the token in LocalStorage

To achieve this I needed to add a few extra libraries and add in a User model, but now I think I have a nice authentication system in place.

Anyway, would you rather I just share this branch for others to see in the future, or would you actually want to add an authentication system to the boilerplate? Or even as a next step after the fullstack branch? It seems like it would be quite a big PR so thought I would ask.

**Comment by diegohaz** [comment]
Hey, @declanelcocks. Sorry for the delay

I'd rather keep things simple, so I wouldn't merge that. If it's easy for you to share that code, I would like to have it as an example. But take your time.

I'm closing this since you found the solution. :)

**Comment by declanelcocks** [comment]
No problem, when I have something I'm happy with I'll post it here 👍

**Comment by ajhool** [comment]
Hey, @declanelcocks have you been able to make any progress here? I'm currently working out authentication using JWTs provided by Auth0 and am stuck determining how to properly authenticate using localStorage, cookies, and server-side rendering. Particularly having trouble reasoning about whether localStorage should have any role in a server-side rendered app.

**Comment by protoEvangelion** [comment]
@diegohaz Can you chime in on this if you have an opinion?

**Comment by declanelcocks** [comment]
@ajhool Sorry for the late reply. Yep, I extended the boilerplate to add in a JWT and github based authentication system to login. I didn't make a PR for it in the end because there was a lot of added code. I added a User model, and several endpoints to create/authenticate users on the API side of things. 

Happy to update the PR here with that code if you want to take a look.

**Comment by ajhool** [comment]
I would very much appreciate that if you wouldn't mind!

**Comment by declanelcocks** [comment]
@ajhool No problem, will have to give me a day or so as I'm currently on vacation and need to rebase my branch.

**Comment by ajhool** [comment]
@declanelcocks Of course! Take your time and if the code ends up being unpolished I'd be happy to polish it and push. I'm working on another project for the next few days so I won't be back to this for a little while anyways.

**Comment by declanelcocks** [comment]
@ajhool Sorry for the super delayed response, but you should be able to take a look at my branch [here](https://github.com/declanelcocks/arc/tree/fullstack-login-extend). By no means is it finished, or perfect, but I believe it should be up-to-date with the latest changes from the `fullstack` branch here.
