### ISSUE TITLE
[fullstack] Session support (inconsistencies between client and server)

### ISSUE THREAD

**Issue by mrsteele** [diegohaz/arc#166]
I wanted to provide this bug as something I have determined to be a complication with the `react-arc` setup.

First, love the approach and I find it to be relatively scalable. Great job to all contributors!

The issue I have found is with the ability for the sessions to work properly on server render and client render. I can maintain the session requests by making a small change to the following line:

https://github.com/diegohaz/arc/blob/710397eb81fd3cfb108b062c33dc9037100800ef/src/services/api/index.js#L26

```diff
    method,
    headers,
+  credentials: 'include',
    ...otherSettings,
```

...that resolves the issue with sessions maintaining as I browse between pages and make requests to the `/api` endpoint.

HOWEVER

The server uses `node-fetch` which is a different library than the client, and the session cookies are not transferred since the server is making the request.

One idea is to forward the cookies from the request made to the router, but its only an idea at this point as I have not spent much time with this and maybe a good issue for someone more familiar with arc to tackle.

Thanks again for a wonderful setup!

**Comment by diegohaz** [comment]
Hey, @mrsteele 

Sorry, I didn't have the time to dig into this.

Well, I usually don't use sessions. I would go for cookies (with `httpOnly` set to `false`).

**Comment by protoEvangelion** [comment]
@diegohaz  Why would you go with cookies over session?

**Comment by mrsteele** [comment]
@diegohaz Wouldn't cookies fall prey to the same issue on server render? The server is the one making the `fetch` request, so you would still need to forward the cookies from the initial client request all the way to the `fetch` request in `services/api`.

I could be wrong, I personally am more familiar with session management.

**Comment by diegohaz** [comment]
I don't think you can access session on client. With cookies (`httpOnly = false`) you can.

Either way you should pass the session/cookie value to redux store on server and grab it on client. Or use only cookies and grab it on client.

**Comment by mrsteele** [comment]
@diegohaz I understand you cannot access the session directly from the client, but in arc's current state all requests made from `services/api` have different cookies/session ids passed because sometimes the server makes the request (with `node-fetch`) and sometimes the client makes the request (with `isomorphic-fetch`).

The closest I got was to making the requests synonymous was to pass the cookies to the `get` method on the page Promise (`req.cookies`).

```javascript
class HomePage extends Component {
  static.get({ store, req }) {
    return new Promise((resolve, reject) => {
      store.dispatch(sessionReadRequest(req.cookies, resolve, reject)
    })
  }

  ...
}
```

This of course required that I also pass this through to the dispatch/sagas and grab it there for use on the reducers. Seemed really convoluted, so I wanted to reach out and mention that the approach is complicated, and most likely not ideal especially since this is different then how the client may interact with the session check api.

**Comment by diegohaz** [comment]
You can easily dispatch a redux action on the server and use a redux selector to grab the cookie/session value on the client, like we are doing here: https://github.com/diegohaz/arc/blob/fullstack/src/server.js#L39

It's not possible to persist state directly from `fetch` between server and client. Even if it was the same library, it would be running in two different processes.

**Comment by mrsteele** [comment]
Got you. I'll try that out. Thanks so much for your help and the project @diegohaz!

**Comment by mrsteele** [comment]
Here is what I got working this weekend. Putting this here so if others have this problem they can use this, and/or someone can tell me I am doing this all wrong 😛 

**App.js**

Since `req` is handed to the App getter, I used that to access cookies from the initial request the client makes to the server.

```javascript
class App extends Component {
  static get({ req, store }) {
    return new Promise((resolve) => {
      // I use this so the app still renders even though the response fails when not logged in.
      // If you still pass a 200, you can remove this and use regular resolve/reject in the dispatch.
      function fakeReject() {
        resolve()
      }
      store.dispatch(sessionReadRequest(req.cookies, resolve, fakeReject))
    })
  }

  ...
```

**actions.js**

Just showing the actual action, where I grab the cookies from the App.get dispatcher

```javascript
export const sessionReadRequest = (cookies, resolve, reject) => ({
  type: SESSION_READ_REQUEST,
  cookies,
  resolve,
  reject,
})
```

**sagas.js**

This is where I grab the cookies from the action and pass that to the api.get request.

```javascript
export function* readSession(cookies) {
  try {
    // pass the cookies from the action to the api.get function.
    const data = yield call(api.get, '/session', { cookies })
    yield put(actions.sessionReadSuccess(data))
  } catch (e) {
    // no session, reject
    yield put(actions.sessionReadFailure(e))
  }
}

export function* watchSessionReadRequest() {
  while (true) {
    // get the cookies from the action dispatch and push those to readSession
    const { cookies } = yield take(actions.SESSION_READ_REQUEST)
    yield call(readSession, cookies)
  }
}
```

**services/api**

I had to make a couple of changes here to accommodate the request. First I had to make sure to grab the cookies and put them in the header (properly formatted as well). I also had to add the `credentials` property to the settings object (this can be added to `otherSettings` as well, but I went ahead and made this a business rule for my application).

```javascript
export const parseSettings = ({ method = 'get', data, locale, cookies, ...otherSettings } = {}) => {
  const headers = {
    Accept: 'application/json',
    'Content-Type': 'application/json',
    'Accept-Language': locale,
  }

  // This is used to forward the cookies
  if (cookies) {
    headers.cookie = Object.keys(cookies).map(key => `${key}=${cookies[key]}`).join('; ')
  }

  const settings = {
    body: data ? JSON.stringify(data) : undefined,
    method,
    headers,
    // this can simply be `include` if you have your api routes on a different domain.
    credentials: 'same-origin',
    ...otherSettings,
  }
  return settings
}
```

**Comment by diegohaz** [comment]
Amazing, @mrsteele.

I would only simply use `store.dispatch(sessionReadRequest(req.cookies, resolve, resolve))`  (or `() => resolve()` if you don't want to pass the error payload) instead of creating a `fakeReject`.
