### ISSUE TITLE
Could you please provide a quickstart CRUD example?

### ISSUE THREAD

**Issue by stanisfun** [diegohaz/arc#169]
BTW great job.
But for a new comer is hard to get pieces connected. Would be nice to have like a quickstart CRUD sample, where all levels gets connected fluently.

**Comment by diegohaz** [comment]
Hey, @stanisfun 

It's better for you to understand react, redux and redux-saga first.

Once you are comfortable with that, have a look at the [resource](https://github.com/diegohaz/arc/tree/ec0f5c11cac6dded774a63e2781d72680c556c5f/src/store/resource) store, which includes the CRUD operations using redux and redux-saga.

**Comment by stanisfun** [comment]
Hahahaha,
nice joke.
Next time if you don't want then just say no(will not do) or whatever else ok.
It's your choice, no one forces you, I just thought that would help to be more usable your approach even for beginners.
Have a nice day

**Comment by protoEvangelion** [comment]
@stanisfun I have tried a few boilerplate projects that deal with CRUD.  If you download the `Fullstack` branch it's actually really easy to get started.  Just download dependencies, fire up mongodb, and start the app.  Pretty simple :)
