### ISSUE TITLE
Fixing the linebreak-style eslint error for Windows

### ISSUE THREAD

**Issue by protoEvangelion** [diegohaz/arc#171]
On Windows, with the current eslint setup, you get this error: `Expected linebreaks to be 'LF' but found 'CRLF'`.

The [eslint site](http://eslint.org/docs/rules/linebreak-style) says this is because Unix and Windows have two different linebreaks.

Is there a better way to fix this besides adding `"linebreak-style": 0,` to the `.eslintrc` file?

**Comment by diegohaz** [comment]
Adding a `.editorconfig` plugin for your IDE/editor solves it?

This file configures the editor to add an `LF` on line endings: https://github.com/diegohaz/arc/blob/master/.editorconfig

**Comment by protoEvangelion** [comment]
I'm using atom.  Do I have to wire it up somehow to make that take effect?

**Comment by ajhool** [comment]
Atom natively supports this feature (see this issue):
https://github.com/atom/line-ending-selector/issues/5

Summary:
Select File->Settings
Select ‘Packages’
Under Core Packages->line-ending-selector, select ‘Settings’
Under the ‘Default line ending’ setting, choose ‘LF’ in the dropdown
You new files will now use LF as the default line ending setting. You can confirm this in the Atom status bar.

**Comment by diegohaz** [comment]
You can also run `npm run lint -- --fix` to get rid of current `CRLF`

**Comment by protoEvangelion** [comment]
Thanks @ajhool  and @diegohaz!  Looks like changing the Atom core package setting to `LF` fixed it :)

**Comment by pashute** [comment]
after `npm install -g babel-eslint`  (had to repeat a few times and after closing windows, finally installed ok...)

change your .eslintrc.js to this: 

    module.exports = {
    //extends: 'airbnb',
    parser: 'babel-eslint',
    env: {
      browser: true
    },
    plugins: ['react'],
      extends: ['eslint:recommended', 'plugin:react/recommended'],
    rules: {
      // overrides
     }
};


`react-native info` gives me this: 

    Environment:
      OS: Windows 10
      Node: 8.11.1
      Yarn: 1.6.0
      npm: 6.0.1
      Watchman: Not Found
      Xcode: N/A
      Android Studio: Version  3.1.0.0 AI-173.4670197

    Packages: (wanted => installed)
      react: 16.3.1 => 16.3.1
     react-native: 0.55.3 => 0.55.3

**Comment by bdjunayed** [comment]
In User settings for the Vscode search crlf, and adjust your settings.

**Comment by chrispincharles** [comment]
I'd the same problem. In the .eslintrc.json file change "line-break-style" to "unix". As CRLF is for Windows and LF is for unix

**Comment by RobFosterNYC** [comment]
I was told that CRLF is for Linux and LF is for windows @ghost

**Comment by EssenceOfChaos** [comment]
@RobFosterNYC - The `LF` setting stands for "Line Feed" and represents the `\n` character. This "backslash n" character represents a newline on Linux and Mac systems. 

The `CRLF` setting stands for "Carriage Return, Line Feed" and represents the combination `\r\n`, which is used on Windows.

Setting the `linebreak-style` in .eslintrc.json to the value "unix", then running ` eslint --fix` should automatically fix the issue.

**Comment by alejandrorossi** [comment]
> ------------------for windows globe in package.son will read all import files---add--
> "rules": {
> "linebreak-style": 0,
> "global-require": 0,
> "eslint linebreak-style": [0, "error", "windows"],

If problem persists, try this, but with "ESLint" instead "eslint"

**Comment by sunny775** [comment]
Simply include this rule to your  .eslintrc.js
`module.exports = {
   . . .
    rules: {
        . . .
       'linebreak-style': ["error", "windows"]
}
}`

**Comment by DineshKachhot** [comment]
> ------------------for windows globe in package.son will read all import files---add--
> "rules": {
> "linebreak-style": 0,
> "global-require": 0,
> "eslint linebreak-style": [0, "error", "windows"],

What about Mac?

**Comment by Emmanuel-Odero** [comment]
You can also run npm run lint -- --fix to get rid of the current CRLF

**Comment by winwin1115** [comment]
I've also had this eslint error.
I have solved by this way.

-Before bug fix:
'rules': {
    'indent': [
      'error',
      2,
      { 'SwitchCase': 1 },
    ],
    'linebreak-style': [
      'error',
      'unix',
    ],
    'quotes': [
      'error',
      'single',
    ],
    'semi': [
      'error',
      'always',
    ],
    'comma-dangle': [
      'error',
      'only-multiline',
    ],
  },
-After bug fix:
'rules': {
    'indent': [
      'error',
      2,
      { 'SwitchCase': 1 },
    ],
    'linebreak-style': 0,         /***** I have fixed this line.
    'quotes': [
      'error',
      'single',
    ],
    'semi': [
      'error',
      'always',
    ],
    'comma-dangle': [
      'error',
      'only-multiline',
    ],
  },

This code is in .eslintrc.js file.

**Comment by just-hope-netizen** [comment]
> You can also run `npm run lint -- --fix` to get rid of current `CRLF`
> 
> You might also be interested on a [**React UI toolkit library**](https://reakit.io) I'm working on.

This solution worked for me
