### ISSUE TITLE
[universal-redux] Adding support for basic styles

### ISSUE THREAD

**Issue by karthikiyengar** [diegohaz/arc#182]
Trying to add basic css support to include third party ones adding a css and style loader.

```
module: {
    rules: [
      { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },
      { test: /\.png$/, loader: 'url-loader?prefix=images/&limit=8000&mimetype=image/png' },
      { test: /\.jpg$/, loader: 'url-loader?prefix=images/&limit=8000&mimetype=image/jpeg' },
      { test: /\.woff$/, loader: 'url-loader?prefix=fonts/&limit=8000&mimetype=application/font-woff' },
      { test: /\.ttf$/, loader: 'file-loader?prefix=fonts/' },
      { test: /\.eot$/, loader: 'file-loader?prefix=fonts/' },
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
    ],
  },
```

For some reason (I guess the babel-register hook?), the css files are getting piped through the JS loader.

```
[0] SyntaxError: Unexpected token .
[0]     at createScript (vm.js:53:10)
[0]     at Object.runInThisContext (vm.js:95:10)
[0]     at Module._compile (module.js:543:28)
[0]     at Module.require._compile (/Users/karthikiyengar/Development/muse-arc/node_modules/webpack-isomorphic-tools/source/index.js:477:29)
[0]     at Module._extensions..js (module.js:580:10)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/Users/karthikiyengar/Development/muse-arc/node_modules/babel-register/lib/node.js:152:7)
[0]     at Module.load (module.js:488:32)
[0]     at tryModuleLoad (module.js:447:12)
[0]     at Function.Module._load (module.js:439:3)
[0]     at Module.require (module.js:498:17)
```

Anything obvious that I'm missing here?

**Comment by karthikiyengar** [comment]
Okay, some quick research pointed me to add the following, just after the babel-core/register hook.
```
require.extensions['.css'] = () => {} // https://github.com/webpack/webpack/issues/1754
```
I would like your thoughts on whether the above setup is reasonable for what I'm trying to achieve.

**Comment by sabarasaba** [comment]
@karthikiyengar I had the same problem, and ended up doing the exact same thing you did.

```
  const cssLoaderConfig = 'css-loader?importLoaders=1!postcss-loader'
   ...
  { test: /\.css$/, loader: DEBUG ? `style-loader!${cssLoaderConfig}` : ExtractTextPlugin.extract({ fallback: 'style-loader', use: cssLoaderConfig }) },
```

and in webpack-isomorphic-tools.js:

```
   ...
    style_modules: {
      extensions: ['css'],

      filter: (module, regex, options, log) => {
        if (options.development) {
          return WebpackIsomorphicToolsPlugin.style_loader_filter(module, regex, options, log)
        }

        return regex.test(module.name)
      },

      path: (module, options, log) => {
        if (options.development) {
          return WebpackIsomorphicToolsPlugin.style_loader_path_extractor(module, options, log)
        }

        return module.name
      },

      parser: (module, options, log) => {
        if (options.development) {
          return WebpackIsomorphicToolsPlugin.css_modules_loader_parser(module, options, log)
        }

        return module.source
      }
    }
  },
...
```

**Comment by karthikiyengar** [comment]
@sabarasaba - Thanks, could you tell me how do you get the extracted CSS to load on `npm run start`?

**Comment by diegohaz** [comment]
@karthikiyengar I'm considering supporting basic CSS, but It increases a lot the webpack config when you want to add other things such as `postcss` and SSR support.

We should definitely create a Wiki page with steps for adding that though.

**Comment by sabarasaba** [comment]
@karthikiyengar  have a look at https://gist.github.com/sabarasaba/5a4add0ac458dbbab721c1f7fe2175e0. It's an extract from what I'm doing in my project, it has a few things that you probably dont need but you'll get the gist of it. Lemme know if you have any doubts.

**Comment by karthikiyengar** [comment]
@sabarasaba - Thank you so much for your gist. I tried it out, had a few hiccups here and there. Will give it a shot again once I have the time.

For now, I'm just using `injectGlobal` to get stuff moving.

**Comment by sabarasaba** [comment]
@karthikiyengar awesome, lemme know how it goes man. If you still have doubts just hit me up, or if you have a public repo that I can jump in to help 😄

**Comment by rvenugopal** [comment]
@deigohaz Is there a plan to create documentation in the wiki like you mentioned in this thread?

Thanks
Rv

**Comment by diegohaz** [comment]
@rvenugopal Since we are using [`webpack-blocks`](https://github.com/andywer/webpack-blocks), I'm waiting for the 1.0 release (https://github.com/andywer/webpack-blocks/issues/134) to add `css-modules`, `extract-text`, `postcss` and everything to support css modules.

**Comment by rvenugopal** [comment]
@diegohaz Thanks for your response.  I will keep my eyes for the 1.0 release
