### ISSUE TITLE
[redux] Example of radio buttons or select drop down in form?

### ISSUE THREAD

**Issue by protoEvangelion** [diegohaz/arc#184]
I'm having some trouble implementing ReduxForm using radio buttons and the select drop down field.  

I noticed there is a great example under the **PostForm** component but it only includes `text` and `textarea` input types.  

_Could you provide an example that shows how to use **radio buttons** and **select input** fields?_

**Comment by diegohaz** [comment]
Hey, @protoEvangelion 

You may find better answers on `redux-form` specific channels. 

The redux-form website has a pretty good example on that: http://redux-form.com/6.5.0/examples/simple/

**Comment by protoEvangelion** [comment]
@diegohaz Thanks :)  I fixed the radio button by not passing the **ReduxField** component. _Will that diminish SSR compatibility at all if I do not pass it in?_  Here is the way that wasn't working (_buttons when clicked would not show up as selected_):

```jsx
     <Field name="male" label="Male" type="radio" component={ReduxField} />
     <Field name="female" label="Female" type="radio" component={ReduxField} />
```

Here is the example from http://redux-form.com/6.5.0/examples/simple/ that is working:

```jsx
     <label><Field name="sex" component="input" type="radio" value="male" /> Male</label>
     <label><Field name="sex" component="input" type="radio" value="female" /> Female</label>
```

**Comment by diegohaz** [comment]
`ReduxField` is just a translator component between `react-router`'s `Field` and our `Field`.

If it isn't working with radio buttons, it's a bug we must fix.

**Comment by protoEvangelion** [comment]
@diegohaz If I click on **male**, it selects it.  When I click on **female** it selects that as well.  However, it does not deselect **male**.

**Comment by diegohaz** [comment]
Try this:
```jsx
<Field name="sex" id="sex1" type="radio" value="male" label="Male" component={ReduxField} />
<Field name="sex" id="sex2" type="radio" value="female" label="Female" component={ReduxField} />
```

**Comment by protoEvangelion** [comment]
@diegohaz Same problem.  Trying to find the fix now...

**Comment by diegohaz** [comment]
> If I click on male, it selects it. When I click on female it selects that as well. However, it does not deselect male.

That's the expected behavior when you have radio inputs with different names like your first example.

I just tested the last code I paste here and that works.

**Comment by protoEvangelion** [comment]
HAHA thanks @diegohaz ...the little things sometimes ;)
