### ISSUE TITLE
issue while deploy

### ISSUE THREAD

**Issue by gemini1988** [diegohaz/arc#187]
Getting this error while deployment ,

Uncaught Error: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

any fix for this ?

**Comment by ajhool** [comment]
Try "npm run dev" to see the full error message and post that

**Comment by gemini1988** [comment]
@ajhool error got fixed  , In html  div with id= app  was missing ,
