### ISSUE TITLE
[universal-redux] Client side data fetching

### ISSUE THREAD

**Issue by karthikiyengar** [diegohaz/arc#190]
The static http method on a component to fetch data for server renders is pretty nifty to use. However, they are not invoked when the initial render has finished and routes change on the client side. An out of the box implementation of such a feature would be handy.

Something on these lines perhaps?https://github.com/reactGo/reactGo/blob/cf5d76e30d0cb94acade147f60a250470ac9d7f1/app/client.jsx

Do let me know if this makes sense to you and I'd be happy to submit a PR.

**Comment by karthikiyengar** [comment]
Here's an implementation of the onUpdate method that works for me:

```

function onUpdate() {
  // eslint-disable-next-line no-underscore-dangle
  if (window.__INITIAL_STATE__ !== null) {
    // eslint-disable-next-line no-underscore-dangle
    window.__INITIAL_STATE__ = null
    return
  }
  const { params, location, components } = this.state
  components.forEach(component => {
    ['post', 'put', 'patch', 'get', 'delete'].forEach(method => {
      if (component[method]) {
        component[method]({ req: null, res: null, store, params, location })
      }
    })
  })
}
```

**Comment by kybarg** [comment]
@karthikiyengar  I use `onEnter` event to fetch data before router renders component. 

```jsx
import React from 'react'
import { Route, IndexRoute } from 'react-router'

import App from 'components/App'
import { HomePage } from 'components'
import { SamplePage, NotFoundPage } from 'containers'

const routes = (store) => {
  const fetchData = (nextState, replace, callback) => {
    const Component = nextState.routes[nextState.routes.length - 1].component
    const canUseDOM = !!(
      typeof window !== 'undefined' &&
      window.document &&
      window.document.createElement
    )

    if (typeof Component.get === 'function' && canUseDOM) {
      Component.get({ store, ...nextState })
        .then(() => callback())
        .catch(error => {
          callback(error)
        })
    } else {
      callback()
    }
  }

  return (
    <Route path="/" component={App}>
        <IndexRoute component={HomePage} />
        <Route component={SamplePage} onEnter={fetchData} />
        <Route path="*" component={NotFoundPage} />
      </Route>
    </Route>
  )
}

export default routes

```

**Comment by mrsteele** [comment]
After thinking about it, I wonder if we took a hybrid approach.

Similar to how the page getters render the required content on the server for the initial load, maybe we can leverage that for the router "onEnter" hooks.

This have a similar approach to what @kybarg has suggested but it lets the pages manage that instead of writing new onEnter functions for each page that needs it.

Thoughts?

**Comment by protoEvangelion** [comment]
@kybarg Is there an advantage to using `onEnter` versus `onUpdate` ?

**Comment by kybarg** [comment]
@protoEvangelion Not sure, this is fast workaround according to [docs](https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#enter-and-leave-hooks)

**Comment by protoEvangelion** [comment]
@kybarg Thanks!

**Comment by karthikiyengar** [comment]
@kybarg - I haven't tried out your logic yet, but I think it would cause a repeated request on the client if the data is already fetched on the server? 

Something that this snippet takes care of?

```
if (window.__INITIAL_STATE__ !== null) {
    window.__INITIAL_STATE__ = null
    return
}
```

Let me know your thoughts.

**Comment by kybarg** [comment]
@karthikiyengar that is just example. You can modify it any way you need

**Comment by diegohaz** [comment]
Solved it in `redux-ssr`. Relevant code: https://github.com/diegohaz/arc/blob/b484b41bbdfd15919b4a06d4fd6b92fb05293269/src-example/containers/PostList.js#L27-L35
