### ISSUE TITLE
[fullstack] deploy to vps

### ISSUE THREAD

**Issue by zj5121** [diegohaz/arc#191]
I'm trying to deploy the 'fullstack' to my vps, the code can run:
$ NODE_ENV=production node .
Listening on server http://127.0.0.1:8080

but when I run curl to fetch the content:
$ curl localhost:8080
Moved Permanently. Redirecting to https://127.0.0.1/

What's wrong with it? is there anything I need to config?
Thanks!

**Comment by diegohaz** [comment]
Production mode enables `https` redirect by default. You may want to disable it on `src/services/express` or enable SSL handling on localhost.

**Comment by zj5121** [comment]
good, after disable it, it works!
Thanks for your help :)
