### ISSUE TITLE
[Style engine] Make styled-components as optional dependency

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#194]
The idea is to to move style engine away from **core** so it would be easier to keep projects that use **Arc** up to date. Cause now I always need to keep in mind changes I've made to core code. To make it happen I suggest to use logic similar to one used in [Next.js](https://github.com/zeit/next.js/) Where you don't touch core code but can **hook** it to extend with some custom code.

**Comment by protoEvangelion** [comment]
@kybarg When you say 

> move style engine away from core

how would that affect all of the pre-built components?  

**_Would they still be styled with `styled-components`?_**

**Comment by kybarg** [comment]
@protoEvangelion Why not? As example it can still be `styled-components`. But I want to move styling engine from core so there was no need to touch core components and it was easy to keep core up to date.

**Comment by protoEvangelion** [comment]
@kybarg  When you say core, do you mean the **master branch**?  If we removed `styled-components` from the master branch, would we remove the components folder as well?  Or just style the components using **inline styles**?

**Comment by kybarg** [comment]
@protoEvangelion I mean files under `src-clean` folder. The ideal way would be to be able to keep **Arc** as separate package like [https://github.com/zeit/next.js/](https://github.com/zeit/next.js/)

**Comment by protoEvangelion** [comment]
@kybarg That makes sense.  Do you think it would be better to use inline styles or no styles at all?

**Comment by diegohaz** [comment]
Closing this as #213 solves part of it.

The Next.js part (which I love) is something we could do in the future, but probably it would be another project, not ARc.
