### ISSUE TITLE
[redux] Is there a good way to use containers in StoryBook?

### ISSUE THREAD

**Issue by ShaunGreiner** [diegohaz/arc#196]
I'm working on a project and I would like to preview containers inside of StoryBook, but I see it isn't hooked up to redux. Is there a best way to set this up?

**Comment by diegohaz** [comment]
Couldn't you simply `import { Container }  from 'containers'` on an index.stories.js file?

`.storybook/config.js` already set up redux.

**Comment by ShaunGreiner** [comment]
Ah, I was being dumb, my StoryBook config was generated from another branch somehow.

Thanks for creating this kit, my team is loving it so far.
