### ISSUE TITLE
[redux] Question about deployment

### ISSUE THREAD

**Issue by jaydlawrence** [diegohaz/arc#203]
I cloned the repo, ran it and then tried to build it to see how it works for deployment.

What is the idea behind npm run build?
Is it suppose to compile everything into static HTML and Js so that it can be accessed directly or does it still need a webserver?

My assumption after building it for deployment was that I could go to <repo_path>/dist/index.html in my browser and be able to access the minimised static version of the site.
It is currently blank when I do that.
Is that not the case? Or is it what it is supposed to do, but I broke it somehow?

Sorry for the n00b question, I am relatively new to "new" JS frontend development with all the tools etc.

Thanks
Jayd

**Comment by zj5121** [comment]
I believe the wiki about the deployment should be updated now, so many people needs help on this topic.
since it has 4 branchs for 4 different purpose, it make it worse and confusing.

**Comment by diegohaz** [comment]
> Is it suppose to compile everything into static HTML and Js so that it can be accessed directly or does it still need a webserver?

It can be accessed directly, but you'll need a webserver (actually, `react-router` needs that).

Any help on Wiki will be very much appreciated. Please, feel free to update it.
https://github.com/diegohaz/arc/wiki/Deploy
