### ISSUE TITLE
[fullstack] process.env injection

### ISSUE THREAD

**Issue by ajhool** [diegohaz/arc#205]
As far as I can tell, on fullstack, process.env is referenced but is not injected in code anywhere. I plan on adding .env and using the code, below. I just wanted to confirm that there is not another expected way to inject process.env variables that I'm missing (aside from NODE_ENV inline injection in package.json).

npm install --save dotenv

```// /src/index.js
...
import dotenv from 'dotenv'
dotenv.config()
...
```

PS. Do people prefer using "source env.sh" instead of dotenv?

**Comment by protoEvangelion** [comment]
You can use [Webpack's Define Plugin](https://webpack.js.org/plugins/define-plugin/).

However, I prefer to use **dotenv** and then when deploying to Heroku for instance and adding those variables in the online config.

**Comment by ajhool** [comment]
Thanks for the response @protoEvangelion , sounds good to me.
