### ISSUE TITLE
[idea] Change components import logic

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#209]
Developing app with arc is very fast cause of simple import logic
```javascript
import { Some component } from 'components'
```
But we lose much advantages of classic import like "intellisense" autocomplete and fast navigation in modern editors where you can just click on variable and it navigates to source code.
So what if we could keep classic way of import and still the same speed of development with help of some task runner (gulp, grunt, etc.) which could scan folders for components and write them to `index.js` in components folder then we could import components as simple as and have all the advantages
```javascript
import { Some component } from '../../components'
```

**Comment by diegohaz** [comment]
You can solve it with plugins. I simply use https://github.com/sergiirocks/vscode-ext-node-module-resolve and configure it this way:
![image](https://cloud.githubusercontent.com/assets/3068563/24977138/79054f5a-1fa2-11e7-9d14-181041213e13.png)

**Comment by kybarg** [comment]
@diegohaz thanks a lot
