### ISSUE TITLE
Generator use out-of-date commits

### ISSUE THREAD

**Issue by Ailrun** [diegohaz/arc#218]
By https://github.com/diegohaz/arc/commit/2ddd1e42c080a0902c08adcbce37d3011a5127cd and https://github.com/diegohaz/arc/commit/ad669bc98c13b611f03c56ff7419ef136a919264, broken storybook issue was fixed, but when using the generator, it's still there since the generator use out-of-date (one month or more old) commits.

Could you update those submodules used by the generator?

**Comment by diegohaz** [comment]
Done. Sorry about the delay.
