### ISSUE TITLE
SVG loading

### ISSUE THREAD

**Issue by declanelcocks** [diegohaz/arc#234]
This is actually more of a question than an issue. I just wanted to ask why you chose to structure the `Icon` component the way you did. Originally, I assumed that the way the `require` was working would dynamically include the SVG files if they were/weren't used by the app. But actually, when I looked into it, all the SVG files are included in the bundle, so what's the benefit of using this method? And what is the reason for using `dangerouslySetInnerHTML` rather than straight up including the SVG for example?

Thanks!

**Comment by diegohaz** [comment]
Yeah, all SVG files are included (that's the way webpack handles dynamic requires).

I choose to include the SVG markup into the html (with `raw-loader` and `dangerouslySetInnerHTML`) so we can use css to change its fill color, stroke color etc.

It would not be possible with `url-loader` and `<img />`.

**Comment by declanelcocks** [comment]
Thanks, makes sense 👍
