### ISSUE TITLE
How does importing from "components" work?

### ISSUE THREAD

**Issue by PolyPik** [diegohaz/arc#239]
At first I wanted to use [antd](https://github.com/ant-design/ant-design) with the arc boilerplate, but I encountered difficulties in getting the two to work together. So instead I decided to transfer parts of the arc boilerplate to an antd project. With a bit of effort, things compiled and ran relatively well.

However, I still can't do

`import { SomeComponent } from 'components'`

That line would give me an error.

Instead I have to rely on the [babel-plugin-root-import](https://github.com/entwicklerstube/babel-plugin-root-import) to get the same results with the following line.

`import { SomeComponent } from '~/components'`

So what do I need to install and what do I need to configure in order for  `import { SomeComponent } from 'components'` to work?

**Comment by diegohaz** [comment]
That's a webpack config: https://github.com/diegohaz/arc/blob/master/webpack.config.js#L57

`sourceDir` will be `src` by default.
