### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by justinmasse** [diegohaz/arc#246]
Has anyone implemented a localization solution with this framework? I'm planning to use this for my next internal project, will require localization support for up to four different languages. Would love any discoveries or tips that work well with this design structure.

**Comment by diegohaz** [comment]
@7s4r Have you done something related to this?

**Comment by justinmasse** [comment]
I'm playing around with https://www.npmjs.com/package/react-localize-redux right now to see if it integrates well.

**Comment by justinmasse** [comment]
So far it works quite well.  I'm not overly sure if the locale files should live within each components folder yet for example:

Button
   -index.js
   -index.stories.js
   -index.test.js
   -index.locale.js

Or just have a locale folder, at the root of src, much like containers is set up.

Another issue I've run into with this approach is that any component that requires specific locale needs to dispatch it to the store first, I havent found a good flow for this yet, and am finding that if a component needs specific locale that it will likely need a wrapping container. I havent touched storybook yet but I imagine there will be some problems there as well.

**Comment by diegohaz** [comment]
You should be able to use containers within storybook with no problems. I don't know if creating a container for each localized component would be a good approach though.

Take a look at how [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) does that.

**Comment by 7s4r** [comment]
I used [react-intl](https://www.npmjs.com/package/react-intl).

**Comment by 7s4r** [comment]
For the flow with redux:
1) On SSR, I set the language and the country in a store context entity
```
const locale = getLocaleFromHostname(req.hostname)
const lang = getLangFromLocale(locale)
const country = getCountryFromLocale(locale)

store.dispatch(setLang(lang))
store.dispatch(setCountry(country))
```


2) I have a container IntlProvider which is mapped to context entity and call the intlProvider of react-intl package to which I pass the language from store
```
import React from 'react'
import PropTypes from 'prop-types'
import translations from 'translations'
import { IntlProvider } from 'react-intl'
import { connect } from 'react-redux'

const IntlProviderContainer = props => (
  <IntlProvider {...props}>{props.children}</IntlProvider>
)

IntlProviderContainer.propTypes = {
  children: PropTypes.any,
}

const mapStateToProps = state => ({
  locale: state.context.lang,
  messages: translations[state.context.lang],
})

export default connect(mapStateToProps)(IntlProviderContainer)
```


3) I import this container in the app
```
import { IntlProvider } from 'containers'

class App extends Component {
  static propTypes = {
    children: PropTypes.any,
  }

  render() {
    const { children } = this.props

    return (
      <IntlProvider>
        {children}
      </IntlProvider>
    )
  }
}

export default App
```

4) I switch the language when I need with just updating store context

**Comment by justinmasse** [comment]
Yeah they appear to just use one global locale sheet, and opt against using component/container specific localisations.

**Comment by justinmasse** [comment]
Ah you're using SSR @7s4r . I currently had not intended to use that

**Comment by justinmasse** [comment]
@7s4r Do you have a full example of the code? I'm having a tough time understanding it since I'm also new to react SSR.

**Comment by 7s4r** [comment]
@justinmasse You do not have to use SSR. You can set the language on client side.

**Comment by justinmasse** [comment]
Fair point. I've implemented this in the redux branch. Added a locale store, with saga retrieving json files. I just haven't finished the last part, which ties into another problem. 

Before the app loads I would usually check if the user is currently logged in, if so do a rest call to populate the user store, and grab locales and then render the main app. I tried creating an App container and doing these types of queries there(Wrapping the App component), seemed logical. But then my routing broke.

**Comment by justinmasse** [comment]
That's true, I have something implemented. Thanks for the help.

**Comment by declanelcocks** [comment]
Could also store the locale in the cookie/session so it renders the correct language on load with SSR

**Comment by declanelcocks** [comment]
Could also store a locale in the user's cookie/session to make sure you render the locale on SSR
