### ISSUE TITLE
[redux-ssr] - Error: spawn npm ENOENT 

### ISSUE THREAD

**Issue by justinmasse** [diegohaz/arc#247]
Trying to run the base SSR framework on windows 10 and am getting a strange error

```
Happy[jsx-1b1e1e7e]: Version: 3.0.3. Using cache? yes. Threads: 12 (shared pool)
Project is running at http://localhost:3001/
webpack output is served from http://localhost:3001/
Content not from webpack is served from public
404s will fallback to /
Happy[jsx-1b1e1e7e]: Loaded 14 entries from cache. (0 were stale)
Happy[jsx-1b1e1e7e]: All set; signalling webpack to proceed.
Happy[jsx-1b1e1e7e]: Version: 3.0.3. Using cache? yes. Threads: 12 (shared pool)

webpack: Compiled successfully.
Happy[jsx-1b1e1e7e]: Loaded 14 entries from cache. (0 were stale)
Happy[jsx-1b1e1e7e]: All set; signalling webpack to proceed.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by diegohaz** [comment]
Humm, it should be something related to Windows. I don't have Windows here to test it. Could you please try to change https://github.com/diegohaz/arc/blob/redux-ssr/webpack.config.js#L98?

**Comment by justinmasse** [comment]
@diegohaz It does appear to be related to the spawning plugin. If I comment out that line no errors occur.

**Comment by diegohaz** [comment]
Yes, but that works on Mac.

That's necessary to run the server (`npm start`, `node .`, `node dist/server.js`) after server build has finished.

`ENOENT` means "No such file or directory". Maybe it's not finding `dist/server.js`?

**Comment by justinmasse** [comment]
I think so. If I run `node dist/server.js`, `npm start`, or `node .` it works perfectly fine. I'm still flipping through the code seeing if I can find anything, I'm not super amazing with webpack though.

**Comment by diegohaz** [comment]
I updated [webpack-spawn-plugin](https://github.com/diegohaz/webpack-spawn-plugin). Run `npm update` and try again.

**Comment by justinmasse** [comment]
@diegohaz You're the best. Works perfectly now.

**Comment by diegohaz** [comment]
Yay! 🎉
