### ISSUE TITLE
The template components are re-created on every route change

### ISSUE THREAD

**Issue by branchard** [diegohaz/arc#252]
In src-example the template components are re-created on every route change because react will create a separate instance of your Layout for each route.
It's annoying because react will re-generate template's DOM on every route change and every child components of this template will be reset.

Please fix your router architecture.

**Comment by branchard** [comment]
Why did you close my issue?
This is a real problem with your structure.

For example if I put an <input/> in your Header component (in "src-example"), the <input/> will be reset on every route change:
![peek 15-05-2017 19-16](https://cloud.githubusercontent.com/assets/6990948/26070081/8fc6f4d0-39a3-11e7-94eb-434f1a6d6f97.gif)

**Comment by diegohaz** [comment]
I'm sorry, @branchard. I wrote an answer but forgot to send it. 😅

That's how `react-router` works. It re-mounts components on every route change. Since templates are inside pages, they are re-mounted as well.

You need to put those components (e.g. `Header`) outside of the page (e.g. in the `App` component).

**Comment by branchard** [comment]
With Atomic Design methodology `Header` must be in a **page** or a **template**.
There is no other way than to put `Header` outside of the **page** ?

I think it's not optimized/clean to re-mouts whole **template** on each route change :confused:

**Comment by diegohaz** [comment]
You can create an `AppTemplate` and use it on `App`. There's nothing wrong with that.
