### ISSUE TITLE
asset loading

### ISSUE THREAD

**Issue by EricWVGG** [diegohaz/arc#254]
Some information about asset loading (typefaces, bitmaps) in the documentation would be useful. The documentation on the webpack-isomorphic-tools repo is fairly confusing, and does not seem to directly reflect whatever opinionated choices this Arc repo made (I'm not really supposed to include a url like ../../../../public/cats.jpg, am i?)

Thank you, I'm very happy with this framework.

**Comment by diegohaz** [comment]
Is this what you are looking for?
https://github.com/diegohaz/arc/blob/master/src-example/components/atoms/LogoImage/index.js

**Comment by EricWVGG** [comment]
I saw that. Not exactly. I'm going to have a dump of several dozen (or more) images in the /public folder. I'm wondering what the best practice is for addressing images that are there or in a CDN.

**Comment by diegohaz** [comment]
If you put them in the /public folder they will become static files served at `https://yourdomain.com/`. Just refer to them as `/cats.jpg`.

**Comment by EricWVGG** [comment]
I can get http://0.0.0.0:3001/cats.jpg, but not :3000/cats.jpg

**Comment by diegohaz** [comment]
Oh, I see. Which branch are you using?

**Comment by EricWVGG** [comment]
The Redux branch, https://github.com/diegohaz/arc/tree/redux

**Comment by diegohaz** [comment]
Are you sure? There's no port 3001 on the redux project, just 3000. Even on `redux-ssr` (where you have port 3001), you should be able to access `:3000/cats.jpg`

**Comment by EricWVGG** [comment]
Okay, I think I get it now.

"It will start the development server with HMR on top of it.
http://localhost:3000 — Development server
http://localhost:3001 — Webpack assets server (for redux-ssr only)
Now you can open http://localhost:3000 in browser and start developing.”

… so I’m on the redux-ssr branch. Hm.

**Comment by EricWVGG** [comment]
Still fuddling through this, but I imagine it's outside the scope of this repo. Thank you again.
