### ISSUE TITLE
[Question] Conditional rendering components in pages based on redux state, how to do it properly?

### ISSUE THREAD

**Issue by nealoke** [diegohaz/arc#255]
Hi, I'm not directly using this project but I am sure hooked to the methodology and how you guys have implemented it. Currently I've built most of my `atoms`, `molecules` and `organisms` but I would love your input on the following.

What happens when you create a `page` which conditionally renders something based on the redux store. Do you just connect it to redux or do you create a separate container for it?

**Example**
On my download page (dashboard application) I check whether the user has the permission to download with some sensitive data (in this case e-mail addresses), if not, the option is not present. It seems a bit weird to me to create an `organism` or `molecule` then a `container` for this single option when i'm sure this won't be re-used somewhere else.

```
class DownloadPage extends PureComponent {
	render() {
		return (
			<div>
				<div className='MAIN__section'>
					// Other stuff

					<Toggler /> <- always renders, not based on redux state
					{user.permissions.database && <Toggler />} <- based on redux state
					
					// Other stuff
				</div>
			</div>
		);
	}
}
```

Currently I'm using my `pages` to just contain wrapping div's for all the imported `containers ` and `components` to be compliant to the "split your logic from your state" approach suggested by Dan. Should I just connect it? Any input on this would be great!

**Comment by diegohaz** [comment]
Hi, @nealoke. I don't think there's one right answer for that.

What I usually do is creating a container whenever:
- I need to provide an action to the component. If I just need access to the state, it can be easily passed down by a parent component (if that makes sense);
- I want to use that component with its specific behavior in many places. i.e. you will put `<Toggler />` in different places (wrapper components), but still want it to behave the same way (presenting something based on user's permissions).

  A good example of that is a `<SearchBar />`. No matter where you put it, you will want it to do its job (searching).

**Comment by nealoke** [comment]
@diegohaz Thanks for your oppinion!

After fiddling a bit it became clear that I needed to create an `organism` and `container` for this form like component. Can I ask you, is it normal to create a container for each and every form you need to have data from the store to initialize etc?

Still trying to find my way into a more organised and maintainable react / redux project ;)
