### ISSUE TITLE
[redux] Duplication of actions in resources & posts?

### ISSUE THREAD

**Issue by Geczy** [diegohaz/arc#257]
https://github.com/diegohaz/arc/blob/redux/src-example/store/post/actions.js

https://github.com/diegohaz/arc/blob/redux/src-example/store/resource/actions.js

Only thing different is 'entities'

Can we merge this so it isn't duplicating code?

**Comment by diegohaz** [comment]
`resource` is meant to be a generic example of CRUD in redux, while `post` is a slice of it.

We got that on #135 so people can copy and paste (ugh, I know) it to create a basic CRUD store.

In an ideal world, we should be able to reuse `resource` for every CRUD thing, without duplicate code, but I couldn't figure out how to do that yet.

**Comment by diegohaz** [comment]
Closed in #262
