### ISSUE TITLE
displayName undefined for styledComponent override in the same location

### ISSUE THREAD

**Issue by BrandoIsNotASword** [diegohaz/arc#266]
I have a component inside molecules, I can use, without errors inside other component in molecules, but when I tried to override its styles, that's when I get an error with the displanName being undefined.

It only occurs when the components are in the same location.

This is the error I got:
`Uncaught TypeError: Cannot read property 'displayName' of undefined`

**Comment by diegohaz** [comment]
See https://github.com/diegohaz/arc/issues/131#issuecomment-283296269
