### ISSUE TITLE
[redux-ssr] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Inoir** [diegohaz/arc#272]
If the API request throws an error, youll get an UnhandledPromiseRejectionWarning and the page stops working!

Steps to reproduce:
- Check out redux-ssr branch
- Go in src-example/config and change apiUrl to https://jsonplaceholder.com
- Start the app with dev:example command
- See blank page :(

![screen shot 2017-06-09 at 17 20 39](https://user-images.githubusercontent.com/5294072/26982483-d98b9096-4d38-11e7-8678-5ec6eb180a1b.png)

**Comment by diegohaz** [comment]
Thanks for reporting that, @Inoir 

Fixed in d194b7e9578bdf3ad70a1e0d4c09ceca849f164e

**Comment by Geczy** [comment]
@diegohaz the commit says partially, what do you mean by that?

**Comment by diegohaz** [comment]
@Geczy That was a commit on `redux`, which didn't solve the problem completely. The complete is d194b7e9578bdf3ad70a1e0d4c09ceca849f164e
