### ISSUE TITLE
[redux] How to handle chained selectors with the dynamic export?

### ISSUE THREAD

**Issue by nealoke** [diegohaz/arc#274]
I'm wondering how you are correctly importing / exporting chained selectors. For example if you have ´client´ with multiple `accounts`. 

_(simplified example)_

**clients/selectors.js**
`export const getClient = (state) => state.client;`

**accounts/selectors.js (using reselect or anything else)**
`export const getAccounts = createSelector(getClient, (client) => client.accounts)`

Using the following the dynamic export (`store/selectors.js`) will first export the `accounts` and thus the import needed for `getClient` in `accounts` gets an `ùndefined`. 

Any idea on how to solve this?

**Comment by diegohaz** [comment]
This is probably related to https://github.com/diegohaz/arc/issues/131#issuecomment-283296269

You should be able to get it working by doing this:
```js
export const getAccounts = createSelector(
  (...args) => getClient(...args), 
  (client) => client.accounts
)
```

I would try to avoid coupling different redux modules though.
