### ISSUE TITLE
Why no axios ?

### ISSUE THREAD

**Issue by zhDmitry** [diegohaz/arc#279]
It looks like you have implement features and api which axios already has. Also it is lack of features like interceptors and requests canceling? 
Maybe it is useless with saga but with plain react such features are useful.

**Comment by diegohaz** [comment]
We've decided to migrate from `axios` to native `fetch`. See #125 

It should be very easy to use axios on your project though.

**Comment by orther** [comment]
I would love to just use fetch but it's lack of some important functionality at the time of writing this forced me to pick something  xhr based. The two major features I missed:
 - You can not cancel an in-flight request (can't set custom timeout)
 - Not able to track upload progress

Anyways, I wanted To suggest taking a look at [apisauce](https://github.com/skellock/apisauce) (a wrapper around axios) to anyone looking for an xhr based alternative. It's pretty close API wise and was really to just drop in.
