### ISSUE TITLE
[redux] api service doesn't honor header settings?

### ISSUE THREAD

**Issue by Geczy** [diegohaz/arc#282]
https://arc.js.org/sample-page

Visit here and inspect the network for posts?_limit=15

The default header options are missing for the json

```
    Accept: 'application/json',
    'Content-Type': 'application/json',
    'Accept-Language': locale,
```

https://github.com/diegohaz/arc/blob/redux/src-example/services/api/index.js#L20

![image](https://user-images.githubusercontent.com/1036968/27306236-e0d0d654-5512-11e7-9c4b-2a69a7e12696.png)

**Comment by diegohaz** [comment]
Humm, it's working for `GET`/`POST` requests (for me):
![image](https://user-images.githubusercontent.com/3068563/27306755-42c7d308-551d-11e7-97b1-4a9146b8b6bf.png)

But it seems that `OPTIONS` doesn't send those headers. I'm not sure if that's the expected behavior.

**Comment by Geczy** [comment]
Strange, I’m using api.get and it’s sending as options

**Comment by Geczy** [comment]
Thanks, it's fine. Chrome hid it under the Other tab in Network
