### ISSUE TITLE
[redux-ssr] Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by maurya777** [diegohaz/arc#285]
in src/components/Html.js, we are getting the following warning:

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by diegohaz** [comment]
Fixed in #286 thanks to @maurya777
