### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by hseleiro** [diegohaz/arc#297]
Please i need some help, whit the Router, i dont know where to put my Menu component, the router is working, but only if i write it by hand on the url. Where do i put my menu component ? it needs to stay above all my components, for it not disapear. Thanks for the help

**Comment by diegohaz** [comment]
Hi, @hseleiro.

Just use the `App` component.

You can ask these kind of questions on StackOverflow.

**Comment by hseleiro** [comment]
Thanks Diegohaz
