### ISSUE TITLE
Add <meta charset="UTF-8">

### ISSUE THREAD

**Issue by JCQuintas** [diegohaz/arc#300]
I had a problem where latin characters were displayed using the wrong encoding, to fix it I had to add `<meta charset="UTF-8">` to index.html

**Comment by diegohaz** [comment]
Good. Thank you @JCQuintas. Could you send a PR, please?

**Comment by JCQuintas** [comment]
done on #301

**Comment by sudhanshuranjanAki** [comment]
Thanks for a solution but it is not working for us please can you suggest how to add this on our page because we have been trying to add but not working on [website development ](https://srchout.com/website-development-company)  page
