### ISSUE TITLE
Is full lodash required?

### ISSUE THREAD

**Issue by mininternet** [diegohaz/arc#313]
In an effort to keep the production bundle small, would it be possible to only install the required lodash functions, rather than the entire package?

In components would be ```import filter from 'lodash.filter'```

**Comment by diegohaz** [comment]
We use `import filter from 'lodash/filter'` so, even though we have the entire lodash package installed, we only bundle those functions we actually use.

**Comment by mininternet** [comment]
Ah, I see. I'm not a webpack expert, just saw the entire library in package.json, but verified with visualizer that only those functions are being bundled.

![code_packages](https://user-images.githubusercontent.com/3261696/30004683-7965b742-9099-11e7-92ea-85d5a7144daa.png)

I've been installing the individual lodash functions i've needed, but i guess can just import them from the already installed package, good to know.

Thanks!
