### ISSUE TITLE
Upgrade to React 16?

### ISSUE THREAD

**Issue by mininternet** [diegohaz/arc#320]
Are there any plans to upgrade to React 16 now that it's in production? 

https://facebook.github.io/react/blog/

**Comment by diegohaz** [comment]
Sure, would you like to send a PR?

**Comment by mininternet** [comment]
I would like to, but i'm in the middle of launching my current project with a very old version of Arc.

Will be moving on to my next project with the newest version of Arc, so perhaps i will have time then.

**Comment by diegohaz** [comment]
Ok then, I'm gonna keep this open since it will be a very easy first PR for anyone.

**Comment by Geczy** [comment]
Not if 80% of the packages don't support R16 yet :D

**Comment by mininternet** [comment]
The React team put a lot of work into making 16 backwards compatible, up to 15.6 according to them.

(I'd be surprised though if there were actually 0 breaking changes.)

Does seem like a major upgrade though - Fiber, smaller file size, no need for wrapping containers, componentDidCatch, etc., but yes, would require a significant amount of testing, which was my main concern.

**Comment by mininternet** [comment]
Quick update - i upgraded the latest version of ARc to React 16, and had zero breaking changes.

However, my version of ARc differs in that i swapped Styled Components for SASS, and also removed React Modal.

Just an fyi.
