### ISSUE TITLE
How do I have to write integration tests, if all children components should be mocked

### ISSUE THREAD

**Issue by kimslava93** [diegohaz/arc#321]
I've noticed that sub components are mocked, and I see the reason why, but I can't find a way to test business logic of my app. So what if I want to test end user actions with redux form, where sub components are applied? Should I ignore components mock somehow for it?
Sorry if answer is obvious, but I really can't find a way in this situation...

**Comment by diegohaz** [comment]
You can do that with end-to-end tests. See [testcafe](https://github.com/DevExpress/testcafe).
