### ISSUE TITLE
Implement React Portals

### ISSUE THREAD

**Issue by selique** [diegohaz/arc#368]
I try implemet the react 'portal' but i dont undestand why the static file not respond 

i using this exemple like base code https://www.jayfreestone.com/writing/react-portals-with-hooks/

**Comment by BrenoMazieiro** [comment]
Hello @selique!
Can you provide us more information about whatever you are trying to do?
The explanation is a lil bit confusing.

**Comment by selique** [comment]
i discovery the issue its not portal, its a parent element (dropdownlist reactstrap) but its interessanting implement the usePortals with hook on project, has many utilities

**Comment by selique** [comment]
> Hello @selique!
> Can you provide us more information about whatever you are trying to do?
> The explanation is a lil bit confusing.

brazil é nois ! ARC REACT WE ARE BR

**Comment by BrenoMazieiro** [comment]
Have you seen it: https://github.com/diegohaz/arc/tree/master/src-example/components/molecules/Modal
