### ISSUE TITLE
Please, test generator-arc

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/arc#60]
Hi, guys, recently I've released the [`generator-arc`](https://github.com/diegohaz/arc/tree/generator-arc) branch.

![image](https://cloud.githubusercontent.com/assets/3068563/21744321/3e366fd2-d4fa-11e6-8262-c5bba9fc4b26.gif)

I have big plans for it, but first I need to make sure this is stable. I'll really appreciate if you guys start to use it on your projects and give your feedback.

***It should work even if you aren't using ARc***, at least `yo arc:component --ours`, which clones an actual component of yours and automates the process to create a new one.

Just `npm install -g yo generator-arc`, go to your project root and `yo arc:component --ours` (or `--theirs` if you want to grab any ARc's component).

**Comment by hefox** [comment]
Just did "yo arc" then used yo arc:component generate a component and looks to be working fine, will update if not.

(I'm fairly new to react and totally new to arc, but not to using yeoman.)

**Comment by kybarg** [comment]
Works for me as well

**Comment by 0xsven** [comment]
`yo arc:store` produces normalizr schema and middleware files? I was expecting the standard arc store from the docs :)

**Comment by protoEvangelion** [comment]
@diegohaz WOW!  This is a super cool utility and is looking great so far.  However, I am struggling to get `storybook` to work.

I chose the `universal-redux` branch and when I do `npm run storybook` the UI shows up properly on port ***9001*** but does not show any components. I am running Windows 10 on Chrome.  Here is what it looks like:

[![Capture.png](https://s10.postimg.org/5xwky44hl/Capture.png)](https://postimg.org/image/s9udri3lh/)

I think the problem may be in the **generated config file** in the `.storybook` folder.  In `config.js` this statement is throwing an eslint error on the `import theme` statement:

```javascript
import configureStore from 'store/configure'
import theme from 'components/themes/default'
```

*Do you think I am on the right track or am I missing something?*

**Comment by diegohaz** [comment]
@protoEvangelion Thank you for the feedback. 

We need to copy [`src/components/App.js`](https://github.com/diegohaz/arc/blob/master/src/components/App.js) and [`src/components/themes`](https://github.com/diegohaz/arc/tree/master/src/components/themes) to the `src-clean` folder.

Do you want to send a PR against the master branch with that change?

**Comment by diegohaz** [comment]
@0xsven It just copies the current store folders on the boilerplate or on your code. Wasn't this what you expected?

**Comment by protoEvangelion** [comment]
@diegohaz Sure thing!  Just made the PR.  By the way, I met Michael Jackson yesterday the creator of React Router and he said they are releasing **_React Router 4_** before React Conf on Monday.  When you want to make the switch from **version 3 to 4** I would be happy to help :)

**Comment by diegohaz** [comment]
@protoEvangelion Wow! Good to know that. 

ARc had RR4 on the early versions (see [v0.2.1](https://github.com/diegohaz/arc/tree/v0.2.1) and the [v0.3.0 patch notes](https://github.com/diegohaz/arc/releases/tag/v0.3.0) to understand the reason we downgraded).

Well, since #92 we don't need the scroll management anymore.  We could already add RR4 on `master` today. But for the `redux` branch, we need to wait for [react-router-redux](https://github.com/reactjs/react-router-redux) to support RR4 or use another equivalent solution. 

On `universal-redux` and `fullstack` we need to make sure that RR4 works well with SSR and our [fetchData approach](https://github.com/diegohaz/arc/tree/universal-redux#universal) (otherwise we should change that approach).

That said, the project was designed this way (separated in branches) so we can handle better this situation. If RR4 works on master, let's do that asap, we can upgrade other branches later (see https://github.com/diegohaz/arc/issues/112#issuecomment-280871470 where I talk exactly about it).

Your help is very welcome.

**Comment by diegohaz** [comment]
Just created an issue for RR4 upgrade: #161

**Comment by protoEvangelion** [comment]
@diegohaz Just an idea, is there any way to make searching case **insensitive**?  For instance, if I search for **h**ero after running `yo arc:component` nothing will show up.  I have to search for **H**ero for it to show up.

**Comment by diegohaz** [comment]
@protoEvangelion We are using [inquirer-autocomplete-prompt](https://github.com/mokkabonna/inquirer-autocomplete-prompt) here to find components: https://github.com/diegohaz/arc/blob/generator-arc/src/component/index.js#L42-L48

I'm not sure if it has case option though.

**Comment by protoEvangelion** [comment]
@diegohaz I would be happy to test this, but am unsure how to make that happen in a yeoman enviroment.
