### ISSUE TITLE
Follow the Object Rest Destructuring specification

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/arc#68]
https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Rest.md

Currently, we are breaking this rule on some component props destructuring:
```js
let { ...x, y, z } = obj; // syntax error
```

The components are:

- [Input](https://github.com/diegohaz/arc/tree/master/src/components/atoms/Input/index.js)
- [Link](https://github.com/diegohaz/arc/tree/master/src/components/atoms/Link/index.js)
- [Feature](https://github.com/diegohaz/arc/tree/master/src/components/molecules/Feature/index.js)
- [IconButton](https://github.com/diegohaz/arc/tree/master/src/components/molecules/IconButton/index.js)
- [IconLink](https://github.com/diegohaz/arc/tree/master/src/components/molecules/IconLink/index.js)
- [Modal](https://github.com/diegohaz/arc/tree/master/src/components/molecules/Modal/index.js)
- [Table](https://github.com/diegohaz/arc/tree/master/src/components/molecules/Table/index.js)

The solution is probably as simple as changing this:
```js
const Feature = ({ icon, title, link, children, ...props, soon }) => {
```
to this:
```js
const Feature = ({ icon, title, link, children, ...props }) => {
  const { soon } = props
```

I'll leave this issue here for a while for the case of someone wants to contribute.

**Comment by antoinerey** [comment]
What does produce ?

```js
const Feature = ({ icon, title, link, children, ...props, soon }) => {
```

Does it :
1. make `soon` available as variable
1. but, does not extract `soon` from `props` (so `props.soon` exists) ?

**Comment by diegohaz** [comment]
> make soon available as variable
but, does not extract soon from props (so props.soon exists) ?

Exactly. This is currently possible with Babel, but isn't in the spec, so might break in the future.

**Comment by diegohaz** [comment]
Maybe just changing references from `too` to `props.too` should be more elegant. I don't know, only IconButton has many variables after props.
