### ISSUE TITLE
[fullstack] not start after install using instructions from the readme.md

### ISSUE THREAD

**Issue by jt3k** [diegohaz/arc#71]
# The problem
![screenshot](https://i.imgur.com/aqZMIWU.png)

i have no idea how to start

### env info:
osx 10.11.6
![npm 3.10.10   node v 7.2.1](https://i.imgur.com/3eTmPHs.png)

**Comment by diegohaz** [comment]
I see you are trying to run the fullstack branch.

You need the [MongoDB](https://www.mongodb.com/) service to run it. Just install it and keep `mongod` running.

Oh, and it's missing in readme, thank you for noticing.

**Comment by jt3k** [comment]
this solution helps me:
```bash
brew update
brew install mongodb
mkdir -p ~/work/mongodb-data/db # <-- folder in which data will be saved
mongod --dbpath ~/work/mongodb-data/db # too
npm run dev # <-- run the ARc
```
