### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/arc#83]
![image](http://i.giphy.com/MPCgca1EuZlLi.gif)

I never touched webpack 2 and will not be able to dig into this for the next few weeks. So I will really appreciate if someone could help. :)

Let's do this.

**Comment by steven-haddix** [comment]
Just converted another project pretty quickly. Could take a stab at getting the basics converted.

**Comment by diegohaz** [comment]
@steven-haddix Yes, please. <3

**Comment by steven-haddix** [comment]
[Webpack 2 Conversion](https://github.com/diegohaz/arc/pull/91)

**Comment by diegohaz** [comment]
Done in #91 by @steven-haddix  🎉

I merged it with other branches and apparently everything is working fine. If someone finds a problem, please open a new issue.
