### ISSUE TITLE
npm run build generates a non working bundle

### ISSUE THREAD

**Issue by sabarasaba** [diegohaz/arc#84]
Heya,

First of all I wanted to say thank you! The project looks amazing, and it solves a lot of the hassle of setting up a new project. 

I cloned the repo, switched to the `universal-redux` branch, installed the deps and then ran `npm run build` and that gave me the following:

```
~/Projects/arc  ~universal-redux~                                                                                                                                                               
▶ l dist
total 1672
drwxr-xr-x   5 ignacio  staff   170B Feb  4 16:28 .
drwxr-xr-x  20 ignacio  staff   680B Feb  4 16:28 ..
-rw-r--r--   1 ignacio  staff   777K Feb  4 16:28 app.016e79d8bb4ff4009cf6.js
-rw-r--r--   1 ignacio  staff   8.5K Feb  4 16:28 icon.png
-rw-r--r--   1 ignacio  staff    41K Feb  4 16:28 thumbnail.png
``` 

I tried running `node app.016e79d8bb4ff4009cf6.js`(v7.2.0) but it throws a `window is not defined`. Is there anything I'm missing?

Thanks.

**Comment by diegohaz** [comment]
Hey, @sabarasaba 

The `app.016e79d8bb4ff4009cf6.js` file is the client bundle. To run the server you need to `npm start`.

Tell me if it solves your problem.

**Comment by sabarasaba** [comment]
That makes a lot of sense! worked like a charm. Obrigado papi
