### ISSUE TITLE
Remove server scripts after load.

### ISSUE THREAD

**Issue by kybarg** [diegohaz/arc#89]
After page load react regenerates styles and it causes duplicates of same the styles.

BTW - Thnak you so much for your boilerplate! It's awesome. Smth I wanted to do myself but haven't time for 😄

**Comment by diegohaz** [comment]
Hey, @kybarg. Thanks! :)

This is an issue related to `styled-components` and should be fixed soon in `v2`.

You can refer to this thread on the styled-components repo: https://github.com/styled-components/styled-components/pull/214#issuecomment-267519606

**Comment by kybarg** [comment]
@diegohaz Now I'm deleting styles with script placed before closing `</body>`
As I understand you're saying in `v2 ` styles not going to be regenerated? It would be even better then I expected then)
