### ISSUE TITLE
Not found page on universal rendering

### ISSUE THREAD

**Issue by adrianha** [diegohaz/arc#9]
Hi diegohaz, Great boilerplate!
By the way, could you give some example or proper way to render not found page when fetching non existing data from API?

**Comment by diegohaz** [comment]
Thank you, @adrianha.

I've added a `NotFoundPage` to the boilerplate. Use this commit as reference: 406fc484bd95b88ea9bce5fccca9602753ab0187

Demo: https://arc.diegohaz.com/dsda

**Comment by adrianha** [comment]
Thanks @diegohaz for the example.
by the way, if i want to fetch some data from API first before decide it to show actual page or show not found page.
let's say, someone go to 

> mysite.com/product/12345

 which is 12345 is product id and its not exists in the database; then i want to show not found page. how can i handle it?

**Comment by diegohaz** [comment]
You can use the [`onEnter`](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#onenternextstate-replace-callback) property of `react-router`.
