### ISSUE TITLE
Static get request with params

### ISSUE THREAD

**Issue by declanelcocks** [diegohaz/arc#95]
I really like the static get request that you added to the posts endpoint in the arc example and I'm trying to implement something similar with the boilerplate. Have you thought about how you'd handle API requests with parameters using this approach? I want to take some query params from the URL and use them in the API request if possible.

For example my path in react-router is "/:param1-:param2?queryParam=5"

**Comment by diegohaz** [comment]
The static method receives the express request object as you can see here: https://github.com/diegohaz/arc/blob/638aeccbfed610f91904730a394f21c4d554c1bb/src/server.js#L55

So you can use `req.query` to get the query parameters.

Does this answer your question?

**Comment by declanelcocks** [comment]
Thanks for the quick reply. Do you mean to acces the request object in server.js? I tried that and while it would work I wasn't sure that would be too scalable as I would have to create a special case for this route. Express will see the query object but it won't know what the react-router params are correct? In my example that's the two params in the path

**Comment by diegohaz** [comment]
You can access them in the static method of the container component (e.g. https://github.com/diegohaz/arc/blob/638aeccbfed610f91904730a394f21c4d554c1bb/src/containers/SamplePage.js)

It also passes the react-router `params` object.

**Comment by declanelcocks** [comment]
Great, I completely missed the fact you're passing all of those values into the `static` methods. I'm not sure where you have access to the react-router `params` object though? If I have a URL like `/:paramName` it will not be picked up anywhere in the request object?

**Comment by diegohaz** [comment]
Not stupid at all. Other people may also have the same question.
Glad you figured it out.
