### ISSUE TITLE
Add storyshots

### ISSUE THREAD

**Issue by abhishekisnot** [diegohaz/arc#96]
Storyshots are basically Jest Snapshots to test  Storybook. https://github.com/storybooks/storyshots

**Comment by diegohaz** [comment]
Hey, @abhishekisnot 

I've been thinking about that, but had no time to dig into it yet.

I don't want to add unnecessary complexity to the boilerplate, but this seems to be really simple. Would you mind to send a PR so we can see that working?

**Comment by abhishekisnot** [comment]
Hi @diegohaz, I'm gonna give it a shot tonight and tomorrow and see how it goes.

**Comment by diegohaz** [comment]
Closing as discussed in #101
